In [15]:
import torch
import numpy as np

## Numerical Limit vs Pytroch's Autograd

In [31]:
def f(x):
    return 3*x**2-4*x

def numerical_lim(f,x,h):
    return (f(x+h) - f(x))/h

h = 0.1
for i in range(6):
    print(f"h={h:.6f}, numerical limit = {numerical_lim(f,1,h)}")
    h*=0.1

h=0.100000, numerical limit = 2.3000000000000043
h=0.010000, numerical limit = 2.029999999999976
h=0.001000, numerical limit = 2.0029999999993104
h=0.000100, numerical limit = 2.000299999997956
h=0.000010, numerical limit = 2.0000300000155837
h=0.000001, numerical limit = 2.0000030001021676


In [32]:
x = torch.tensor(1,dtype=torch.float, requires_grad=True)
y = f(x)
y.backward()
x.grad

tensor(2.)

In [33]:
x = torch.arange(4.0, requires_grad=True)
display(x)
y = torch.dot(x,x)
y

tensor([0., 1., 2., 3.], requires_grad=True)

tensor(14., grad_fn=<DotBackward0>)

In [34]:
y.backward()
x.grad == 2*x

tensor([True, True, True, True])

## Autograd for Non-Scalar-Valued Functions

In [35]:
x = torch.arange(3.0, requires_grad=True)
y = x*x
y.backward(torch.ones_like(y)) # behaves as the upstream loss gradient passed down to the current node in the computational graph
x.grad

tensor([0., 2., 4.])

## Optimization using PyTorch Features

In [39]:
x = torch.tensor([-5, -2], dtype=torch.float, requires_grad=True)

import torch.optim as optim
optimizer = optim.SGD([x], lr=0.1)

for i in range(20):
    optimizer.zero_grad()
    loss = f(x)
    loss.backward(torch.ones_like(loss))
    optimizer.step()
    print(loss.detach().numpy().round(2))


[95. 20.]
[14.08  2.08]
[ 1.13 -0.79]
[-0.94 -1.25]
[-1.27 -1.32]
[-1.32 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
[-1.33 -1.33]
