### 2.1 Importing the numpy module
---

In [2]:
import numpy as np

### 2.2 The np.array(...) constructor converts Python iterables into arrays
---

In [3]:
x_array = np.array([1,2,3])
x_array

array([1, 2, 3])

### 3 Datatype of numpy arrays
---

In [4]:
# numpy arrays are homogeneous

x_array.dtype

dtype('int64')

### 3.1 Shape of of numpy array
---

In [5]:
# NDarrays have multiple dimensions or axis along which values are stored
# The magnitudes of each dimension or axis is called the shape of the array
# this size of an array is the total number of elements

print(x_array.shape) # all entries exist along a single axis (dimension 0)
print(x_array.size)

(3,)
3


### 4 Multidimensional arrays
---

| 190 | 170 | 130 |
|-----|-----|-----|
| 105 | 122 | 111 |

- this array has 2 axis or dimensions

- shape is (2,3)

    - the row dimension has size 2

    - the column dimension has size 3

    - coordinates of say 130 would be (0,2)

- all numpy indexing is 0-based

### 4.1 Constructing multidimensional arrays
---

- we can use nested lists to create numpy nd-arrays

In [6]:
x_array = np.array(
    [
        [190, 170, 130],
        [105, 122, 111],        
    ]
)
x_array

array([[190, 170, 130],
       [105, 122, 111]])

### 4.2 Shape of multidimensional array
---

- shape used to be (3,)
- shape will now have two entries

In [7]:
x_array.shape

(2, 3)

### 4.3 Indexing entries in a multidimensional array
---

In [8]:
print("A value = ",     x_array[1,2])
print("Last value = ",     x_array[-1,-1])
print("A row = ",     x_array[0])
print("A column = ",     x_array[:,-1])
print("A subarray = \n",     x_array[:,1:])

A value =  111
Last value =  111
A row =  [190 170 130]
A column =  [130 111]
A subarray = 
 [[170 130]
 [122 111]]


### 5 More array constructors
---
- there are many ways to create an array in numpy

In [9]:
# array of zeros
x_temp = np.zeros((3,3))
x_temp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# array of ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
# creating an array of ones like the array of zeros
x_temp = np.ones_like(x_temp)
x_temp

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# fixed constant array
np.full(shape=(3,3), fill_value=123)

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [13]:
# creating a sequence
np.arange(start=5, stop=16, step=2)

array([ 5,  7,  9, 11, 13, 15])

In [14]:
# creating a sequence of evenly spaced values
np.linspace(start=0, stop=1, num=10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
# custom nd-array filled with random values sampled uniformly from the provided range
np.random.uniform(low=0, high=10, size=(3,3)) # here size behaves like shape

array([[6.12549333, 8.79526781, 1.8443368 ],
       [1.76404435, 5.47721585, 9.38613868],
       [1.94908612, 6.64564252, 4.57587914]])

In [16]:
# same as above but sampling is done from a normal gaussian distribution
np.random.normal(loc=0, scale=1, size=(3,3)) # here loc is the mean, scale is std deviation and size is shape

array([[-0.89256724, -2.07762623, -0.64454352],
       [ 0.7765214 ,  0.56251733, -0.35835478],
       [-0.54273721, -0.03109374, -0.05879028]])

### 6 In-depth indexing of numpy arrays
---

In [17]:
x1 = np.array([5, 0, 3, 3, 7, 9])
print(x1)
print(f"Indexing from the beginning: x1[0] = {x1[0]}, x1[1] = {x1[1]}")
print(f"Indexing from the end: x1[-1] = {x1[-1]}, x1[-2] = {x1[-2]}")


[5 0 3 3 7 9]
Indexing from the beginning: x1[0] = 5, x1[1] = 0
Indexing from the end: x1[-1] = 9, x1[-2] = 7


### 6.3 Indexing single element in multidimensional array
---


In [18]:
x2 = np.array([[3, 5, 2, 4],
               [7, 6, 8, 8],
               [1, 6, 7, 7]])

print(x2,"\n")
print("Negative and positive indexes can be used together:\n")
print(f"x2[0,0] = {x2[0,0]}, x2[2,3] = {x2[2,3]}\n")
print(f"x2[-3,-4] = {x2[-3,-4]}, x2[2,3] = {x2[-1,-1]}\n")
print(f"x2[1,-1] = {x2[1,-1]}, x2[-2,3] = {x2[-2,3]}\n")


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Negative and positive indexes can be used together:

x2[0,0] = 3, x2[2,3] = 7

x2[-3,-4] = 3, x2[2,3] = 7

x2[1,-1] = 8, x2[-2,3] = 8



### 6.5 Subarrays of vectors
---

- slicing is not inclusive of the right bound and when moving in the negative direction, need to specify negative step

In [19]:
x = np.array([[3, 5, 2, 4],
               [7, 6, 8, 8],
               [1, 6, 7, 7]])

print(x,"\n")

print("Use slicing with negative & positive indexing to extract subarrays:\n")

print("Bottom right:")
print(f"x[1:3,-1:-3:-1] =\n {x[1:3,-1:-3:-1]}\n")

print("Bottom left:")
print(f"x[-1:-3:-1,0:2] =\n {x[-1:-3:-1,0:2]}")
print(f"x[1:3,0:2] = \n {x[1:3,0:2]}\n")

print("Bottom middle:")
print(f"x[1:,1:3] =\n {x[1:,1:3]}\n")

print("second column:")
print(f"x[0:,-3] =\n {x[0:,-3].reshape((3,1))}\n")

print("first and last row:")
print(f"x[0:3:2,:] =\n {x[0:3:2,:]}\n")

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Use slicing with negative & positive indexing to extract subarrays:

Bottom right:
x[1:3,-1:-3:-1] =
 [[8 8]
 [7 7]]

Bottom left:
x[-1:-3:-1,0:2] =
 [[1 6]
 [7 6]]
x[1:3,0:2] = 
 [[7 6]
 [1 6]]

Bottom middle:
x[1:,1:3] =
 [[6 8]
 [6 7]]

second column:
x[0:,-3] =
 [[5]
 [6]
 [6]]

first and last row:
x[0:3:2,:] =
 [[3 5 2 4]
 [1 6 7 7]]



### 7 Some array transformations
---

- reshaping can be done so long as the number of elements = product of the axis sizes
    - i.e `[0,1,2,3,4,5,6,7,8,9,10,11]` has 12 elements
    - it can be reshaped into the following nd-array shapes:
        - `(12,1)`
        - `(2,6)`
        - `(6,2)`
        - `(3,4)`
        - `(4,3,1)`
        - `(2,2,3,1)` etc...

In [20]:
x = np.arange(9)
print(x)
x = x.reshape(3,3)
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# this code extracts a subarray of shape (2,2)
# there is then a new dimension inserted at the end creating the shape (2,2,1)
    # this can be thought of as two 2x1 matrices stacked on top of each other
    # as far as output appearance, the last dimension is always the number of columns while the second last is always the number of rows
print(x[0:2,1:,np.newaxis])
print(x[0:2,1:,np.newaxis].shape)

[[[1]
  [2]]

 [[4]
  [5]]]
(2, 2, 1)


In [22]:
# this code extracts a subarray of shape (2,2)
# a new dimension is inserted in the middle creating the shape (2,1,2)
    # this can be thought of as two 1x2 matrices stacked on top of each other
print(x[0:2,np.newaxis,1:])
print(x[0:2,np.newaxis,1:].shape)

[[[1 2]]

 [[4 5]]]
(2, 1, 2)


### 7.2 Array concatenation and splitting
---

In [23]:
# these arrays are stacked along the only dimension that exists which is dimension 0
x1 = np.array([1, 2, 3])
y1 = np.array([3, 2, 1])
np.concatenate([x1, y1], axis = 0)

array([1, 2, 3, 3, 2, 1])

In [24]:
# both arrays now have shape (2,3)
    # for concatenation all off axis sizes need to match
    # concatenating along dimension 0 would stack along dimension 0 (along the rows)
    # concatenating along dimension 1 would stack along dimension 1 (along the columns) 
x2 = np.array([
    [1, 2, 3],
    [-1, -2, -3]
])

y2 = np.array([
    [3, 2, 1],
    [-3, -2, -1]
])

print(np.concatenate([x2,y2], axis=0))
print(np.concatenate([x2,y2], axis=0).shape)
print()
print(np.concatenate([x2,y2], axis=1))
print(np.concatenate([x2,y2], axis=1).shape)

[[ 1  2  3]
 [-1 -2 -3]
 [ 3  2  1]
 [-3 -2 -1]]
(4, 3)

[[ 1  2  3  3  2  1]
 [-1 -2 -3 -3 -2 -1]]
(2, 6)


In [38]:
# here the two arrays are automatically reshaped (1,4) and then stacked vertically

a = np.arange(start=1, stop=5)
b = np.arange(start=5, stop=9)

np.vstack([a,b])
#np.hstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 8 Splitting arrays
---

In [26]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [27]:
# here the array x is split at the specified indecies
    # starting at index 0 and up to but not including index 3 becomes x1
    # starting at index 3 and up to but not including index 5 becomes x2
    # starting at index 5 and up to the last index becomes x3
x1, x2, x3 = np.split(x, [3, 5])
print('x1 =', x1)
print('x2 =', x2)
print('x3 =', x3)

x1 = [1 2 3]
x2 = [99 99]
x3 = [3 2 1]


In [28]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
# vsplit splits along dimension 0
    # grid[0:2,:] becomes upper
    # grid[2:,:] becomes lower
upper, lower = np.vsplit(grid, [2])
print('upper =\n', upper)
print('lower =\n', lower)

upper =
 [[0 1 2 3]
 [4 5 6 7]]
lower =
 [[ 8  9 10 11]
 [12 13 14 15]]


In [30]:
# hsplit splits along dimension 1
    # grid[:,0:2] becomes left
    # grid[:,2:] becomes right
left, right = np.hsplit(grid, [2])
print("left =\n", left)
print("right =\n", right)

left =
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right =
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### 9 Replication
---

- we can use np.repeat() to create a specified number of duplicates for all entries along a given axis
- np.tile allows us to imagine the entire array as a single cell or tile. We can then create a super array of a specified shape where each "entry" is a tile.

In [31]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
# each row is repeated 2 times
np.repeat(x, 2, axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [33]:
# the array x is now a single tile creating a larger array of shape (2,2)
np.tile(x, (2,2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])